Repository TomerFi/version-bumper, pull requests merged in 2022-10, with the labels that each got.

#96 ci(syntax): fix deprecated actions syntax
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/stage.yml
Labels: status: approved, size: s, hacktoberfest-accepted

#99 docs: better community docs
  .all-contributorsrc
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  Makefile
  README.md
Labels: status: needs review, size: l

#101 chore: added make file enable-multiarch target
  CONTRIBUTING.md
  Makefile
Labels: status: needs review, size: s, hacktoberfest-accepted
